✨ Delete Dataservice entities
kids-first/kf-utils-python pull request #24
Opened 2021-03-19 03:35 UTC by znatty22

Closes #23 

Delete entities in Dataservice by study id or blanket delete all entities in Dataservice

## TODO
- [ ] Should we add something that checks the host URL and prompts the user for confirmation if the host is not localhost?
- [ ] README entry

2021-03-19 03:37 UTC, znatty22 commented on tests/conftest.py
> +@pytest.fixture
I know this seems silly for testing delete_entities since this fixture uses the thing we're going to test lol, but we need some way to cleanup the dataservice for all of the integration tests that make use of the live dataservice. That's also why I added unit tests for delete_entities that make use of mocks

2021-03-22 16:41 UTC, fiendish commented
You don't want to just call DELETE on the study endpoint until the data service stops erroring? 🤣

2021-03-22 21:38 UTC, znatty22 commented
> You don't want to just repeatedly call DELETE on the study endpoint until the data service stops erroring? 🤣

Lol nooo, that would crash it for the big studies esp the ones that have the cohort VCFs

2021-03-29 18:06 UTC, fiendish requested changes

2021-03-29 18:06 UTC, fiendish commented on kf_utils/dataservice/delete.py
> +    "studies",
It seems like the 'studies' entry in ENDPOINTS is only used by one test. It probably makes more sense to put studies into its own constant and not include it here and then add a separate studies endpoint check in that one test so that you don't have to have `[:-1]` everywhere.

2021-03-29 18:06 UTC, fiendish commented on tests/conftest.py
> +@pytest.fixture
lol no I love it

2021-03-29 19:08 UTC, fiendish commented on kf_utils/dataservice/delete.py
> +    for i, kf_id in enumerate(kfids):
nothing changed lol

2021-03-29 19:18 UTC, znatty22 commented on kf_utils/dataservice/delete.py
> +    for i, kf_id in enumerate(kfids):
Oh i see, oops. One sec

2021-03-29 20:02 UTC, fiendish approved these changes

2021-03-29 20:02 UTC, merged